# Generated by Django 5.1.3 on 2024-12-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(default=9, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(default=2000, max_length=4),
            preserve_default=False,
        ),
    ]
